### ISSUE TITLE
Finalize dynamic allocation memory to NULL

### ISSUE THREAD

**Issue by purplepig4657** [hygoni/precise-leak-sanitizer#29]
If previous dynamic allocated memory has dynamic allocation memory pointer value, it can lead sanitizer to error.

We have to finalize dynamic allocation memory to NULL when free called.

**Comment by hygoni** [comment]
It should be better to set to NULL only when the value is a valid pointer to heap area.

**Comment by hygoni** [comment]
- [ ] As we discussed, you need to initialize to 0 (NULL) when allocating memory, not when freeing memory because memory allocator can update the content of a freed object.

- [ ] Also - for stack variables, let's initialize to NULL for unwelcome surprises.
