### ISSUE TITLE
LSan & PLSan Integeration

### ISSUE THREAD

**Issue by kimseongyu** [hygoni/precise-leak-sanitizer#32]
There are two ways to integrate LSan and PLsan:
1. Whenever PLSan detects a memory leak, stop the world and let LSan scan memory, and then report it only if LSan detects it. 
2. Just like LSan, report when program exits. To do this, PLSan must save leak data structures when it detects a leak. When program exits, LSan scans the memory, and creates its own leak data structure. But instead of LSan reporting, it passes its own leak data structures to PLSan. In other words, LSan passes leak structures to PLSan, and PLSan considers it with its own leak data structure when reporting.

We will try No. 2 first.

- [ ] PLSan stores object address and lost trace when a leak occurs
- [ ] in LSan, do not report and pass leak data structures to PLSan **only when PLSan is enabled**
- [ ] For PLSan, if (alloc trace, lost trace) is the same, two leaks are the same. **However, when report_objects=1**, it reports individual leaked objects.

**Comment by hygoni** [comment]
Closed by #39
