### ISSUE TITLE
Drop shadow memory and use metadata for reference counts

### ISSUE THREAD

**Issue by hygoni** [hygoni/precise-leak-sanitizer#33]
- [ ] Drop all functions for reference counting in the runtime library (mmap() part, refcount init, refcount reset after free, refcount increase/decrease in StoreInst)
- [ ] Reference count is moved from shadow memory to struct ChunkMetadata in LSan
       Write new functions in PLSan runtime library that manages reference counts
- [ ] Modify `struct ChunkMetadata` to save reference count in it, but do not increase sizeof(struct ChunkMetadata), but use `union` feature in C++, with 'allocated' variable in the structure
- [ ] LLVM Pass should be modified to call the new reference counting function

**Comment by qoqh21** [comment]
Is it right that I modify 8 files?

- PreciseLeakSanitizer.cpp and .h
- plsan.cpp and .h
- plsan_handler.cpp and .h
- plsan_shodow.cpp and .h

**Comment by hygoni** [comment]
> Is it right that I modify 8 files?
> 
> * PreciseLeakSanitizer.cpp and .h
> * plsan.cpp and .h
> * plsan_handler.cpp and .h
> * plsan_shodow.cpp and .h

You also need to update LeakSanitizer implementation a little bit,
- so maybe lsan_allocator.cpp and h, lsan_common.cpp and h
because you need to change the definition of `struct ChunkMetadata`

Also, to modify reference count in PreciseLeakSanitizer runtime library, you need to include and use some helper functions that LSan uses, like
- the  function that converts object address to metadata address

**Comment by qoqh21** [comment]
I put a code in the plsan_allocator that doesn't seem to have anything to do with hwasan in hwasan.
I'm trying to build it, but there's still an error, so I think I'll have to do a little more.
