### ISSUE TITLE
Handle local pointer variable with stack pointer.

### ISSUE THREAD

**Issue by purplepig4657** [hygoni/precise-leak-sanitizer#34]
Currently, we count reference local pointer variable when end of function with static method(Just collect alloca instruction).
I'll change this method to read memory space that pointed by stack pointer and frame pointer.

- [ ] Push frame pointer to stack
- [ ] Push stack pointer to stack
- [ ] Reference count every 8byte in local variable space (assume machine is 64bit)
- [ ] Reference count every 8byte in dynamic allocated space
- [ ] Change reading stack pointer, frame pointer register to support the other machine.
- [ ] Change reference count to support 32bit machine.

**Comment by hygoni** [comment]
I figured out that zeroring area between the frame pointer and the stack pointer might not be the right solution for this.

In C++ Constructors, the address of `this` is inserted into stack, but it is stored _before_ __plsan_initialize_stack(). I don't understand the exact cause, but it seems the CPU backend rearranges alloca and __plsan_initialize_stack.

Therefore I think an alternative solution would be to zero-initialize stack variables using `-ftrivial-auto-var-init=zero`, and then implement similar thing for zero-initializing
